version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  acme:
    driver: ${VOLUMES_DRIVER}


services:
  ### NGINX-Proxy #################################################
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost.d
      - ${APP_CODE_PATH_HOST}:/usr/share/nginx/html
      - ${NGINX_SSL_PATH}:/etc/nginx/certs:ro
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ./nginx/logrotate/nginx:/etc/logrotate.d/nginx
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - frontend
      - backend
      #- bridge  # uncomment this to allow communicate with external containers 
    restart: unless-stopped

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost.d
      - ${NGINX_SSL_PATH}:/etc/nginx/certs:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    depends_on:
      - nginx-proxy
    networks:
      - backend
    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost.d
      - ${APP_CODE_PATH_HOST}:/usr/share/nginx/html
      - ${NGINX_SSL_PATH}:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
      - docker-gen
    networks:
      - backend
    restart: unless-stopped
