version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  acme:
    driver: ${VOLUMES_DRIVER}


services:
  ### NGINX-Proxy #########################################
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost.d
      - ${APP_CODE_PATH_HOST}:/usr/share/nginx/html
      - ${NGINX_SSL_PATH}:/etc/nginx/certs:ro
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ./nginx/logrotate/nginx:/etc/logrotate.d/nginx
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    
  ###### docker-gen for NGINX-Proxy #######################
  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost.d
      - ${NGINX_SSL_PATH}:/etc/nginx/certs:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    depends_on:
      - nginx-proxy
    networks:
      - backend
    restart: unless-stopped

  ###### LetsEncrypt for NGINX-Proxy ######################
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/vhost.d
      - ${APP_CODE_PATH_HOST}:/usr/share/nginx/html
      - ${NGINX_SSL_PATH}:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
      - docker-gen
    networks:
      - backend
    restart: unless-stopped

  ### Looking-Glass #######################################
  looking-glass:
    image: gmazoyer/looking-glass
    container_name: looking-glass
    ports:
      # - "${LOOKINGGLASS_HOST_HTTP_PORT}:80" # Uncomment to use standalony 
    volumes:
      - ${LOOKINGGLASS_CONFIG_FILE}:/var/www/html/config.php
      - ${LOOKINGGLASS_LOGO_FILE}:/var/www/html/logo.png
      - ${LOOKINGGLASS_LOG_FILE}:/var/log/looking-glass.log
    environment:
      - VIRTUAL_HOST=${LOOKINGGLASS_HOSTNAME} # Comment to use standalony 
      - LETSENCRYPT_HOST=${LOOKINGGLASS_HOSTNAME} # Comment to use standalony 
    depends_on:
      - nginx-proxy # Comment to use standalony 
    networks:
      - backend
    restart: unless-stopped
